[package]
name = "card_format"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gobble = {path="../../mlibs/gobble/"}
failure = "0.1.7"
failure_derive = "0.1.7"
serde = "1.0.106"
serde_derive = "1.0.106"
